name: epic-hand-object-lib
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numpy=1.18.4
  - pandas=1.0.4
  - pillow=7.1.2
  - pip=20.1.1
  - protobuf=3.12.1
  - python=3.7.6
  - setuptools=47.1.1
  - wheel=0.34.2
  - pip:
    - snakemake==5.18.1
